blank_issues_enabled: false
contact_links:
  - name: 🤔 Questions about the library or need help from community?
    url: https://github.com/reaviz/reagraph/discussions
    about: Ask long-form questions and discuss ideas.
