export const shortNodeDescriptions: Record<string, string> = {
  "sabotage van onderzeese infrastructuur (zoals internetkabels)": "Sabotage onderzeese infra",
  "(heimelijke) beïnvloeding en hybride operaties door statelijke actoren die aangrijpen op het maatschappelijk debat)": "Hybride operaties - beïnvloeding maatschappelijk debat",
  "polarisatie rond complottheorieën": "Polarisatie complottheorieën",
  "cyberaanvallen kritieke infrastructuur": "Cyberaanvallen kritieke infra",
  "hitte/droogte": "Hitte en droogte",
  "overstroming zee": "Overstroming zee",
  "klassieke statelijke spionage": "Klassieke statelijke spionage",
  "innovatie nucleaire overbrengingsmiddelen": "Innovatie kernwapendragers",
  "criminele inmenging bedrijfsleven": "Criminele inmenging bedrijfsleven",
  "infiltratie openbaar bestuur": "Infiltratie openbaar bestuur",
  "georganiseerde criminaliteit door heel nederland": "Georganiseerde misdaad",
  "ondermijnende enclaves": "Ondermijnende enclaves",
  "strategische afhankelijkheden grondstoffen en technologie van buitenlande leveranciers": "Afhankelijkheid grondstoffen en tech",
  "crisis in de zuid-chinese zee": "Crisis zuid-chinese zee",
  "tekorten essentiële grondstoffen": "Tekort essentiële grondstoffen",
  "tweespalt in de eu": "Tweespalt eu",
  "verstoring van handel door productieproblemen buitenland": "Handelsverstoring productieproblemen buitenland",
  "uiteenvallen van de navo": "Uiteenvallen navo",
  "tijdelijke bezetting van een eu-lidstaat": "Bezetting eu-lidstaat",
  "onzekerheid energievoorziening": "Onzekerheid energievoorziening",
  "crimineel geweld richting media en overheid": "Geweld media en overheid",
  "anti-overheidsextremisme": "Anti-overheidsextremisme",
  "meervoudige terroristische aanslag": "Meervoudige terroristische aanslag",
  "handelsoorlog waar de eu bij betrokken is": "Handelsoorlog eu",
  "europese schuldencrisis": "Europese schuldencrisis",
  "overstroming rivier": "Overstroming rivier",
  "tekort aan drinkwater door verzilting en vervuiling": "Drinkwatertekort (verzilting/vervuiling)",
  "verarming biodiversiteit met effecten op voedselzekerheid": "Biodiversiteitsverlies (voedselzekerheid)",
  "gebruik van generatieve ai voor deepfakes en desinformatie": "Generatieve ai deepfakes/desinfo",
  "chinese hereniging taiwan": "Chinese hereniging taiwan",
  "cyberspionage overheid": "Cyberspionage overheid",
  "ongewenste buitenlandse inmenging in diasporagemeenschappen": "Buitenlandse inmenging diaspora",
  "keteneffecten elektriciteitsuitval": "Keteneffecten elektriciteitsuitval",
  "ransomware telecom": "Ransomware telecomsector",
  "verstoring van het betalingsverkeer": "Verstoring betalingsverkeer",
  "pandemie door een mens overdraagbaar virus": "Pandemie (mens-op-mens)",
  "natuurbranden": "Natuurbranden",
  "geweldsescalatie rechtsextremisten": "Geweldsescalatie rechtsextremisten",
  "alleenhandelende dader": "Alleenhandelende dader",
  "staatlijke verwerving van een belang in grote telecom-aanbieder": "Staatsovername telecomaanbieder",
  "landelijke black-out": "Landelijke black-out",
  "stralingsongeval in europa": "Stralingsongeval europa",
  "collateral damage": "Collateral damage",
  "systeempartij in de financiële sector in zwaar weer": "Financiële systeempartij in problemen",
  "correctie op waardering financiële activa": "Correctie waardering financiële activa",
  "aanval cloud service provider": "Aanval cloudprovider",
  "ransomware zorgsector": "Ransomware zorgsector",
  "geïnduceerde aardbeving": "Geïnduceerde aardbeving",
  "kerncentrale borssele": "Incident kerncentrale borssele",
  "anarcho-extremisme": "Anarcho-extremisme",
  "uitbraak zoönotische variant vogelgriep": "Zoönotische vogelgriepuitbraak",
  "uitbraak mkz onder koeien": "Mkz-uitbraak koeien",
  "griep pandemie": "Grieppandemie"
};

export const threatImpacts: Record<string, string> = {
    "overstroming zee": "Catastrofaal",
    "pandemie door een mens overdraagbaar virus": "Catastrofaal",
    "is grijpt de macht in marokko": "Zeer ernstig",
    "inzet van kernwapens saoedi-arabië – iran": "Zeer ernstig",
    "geïnduceerde aardbeving": "Zeer ernstig",
    "keteneffecten elektriciteitsuitval": "Zeer ernstig",
    "chinese hereniging taiwan": "Zeer ernstig",
    "tijdelijke bezetting van een eu-lidstaat": "Zeer ernstig",
    "overstroming rivier": "Zeer ernstig",
    "griep pandemie": "Zeer ernstig",
    "uiteenvallen van de navo": "Zeer ernstig",
    "systeempartij in de financiële sector in zwaar weer": "Zeer ernstig",
    "hitte/droogte": "Zeer ernstig",
    "onzekerheid energievoorziening": "Zeer ernstig",
    "aanval cloud service provider": "Zeer ernstig",
    "kerncentrale borssele": "Ernstig",
    "treinramp met gaswolkbrand": "Ernstig",
    "ransomware telecom": "Ernstig",
    "handelsoorlog waar de eu bij betrokken is": "Ernstig",
    "meervoudige terroristische aanslag": "Ernstig",
    "verstoring van het betalingsverkeer": "Ernstig",
    "staatlijke verwerving van een belang in grote telecom-aanbieder": "Ernstig",
    "infiltratie openbaar bestuur": "Ernstig",
    "sneeuwstorm": "Ernstig",
    "crisis in de zuid-chinese zee": "Ernstig",
    "tweespalt in de eu": "Ernstig",
    "crimineel geweld richting media en overheid": "Ernstig",
    "ongewenste buitenlandse inmenging in diasporagemeenschappen": "Ernstig",
    "bestorming en gijzeling tweede kamer": "Ernstig",
    "landelijke black-out": "Ernstig",
    "(heimelijke) beïnvloeding en hybride operaties door statelijke actoren die aangrijpen op het maatschappelijk debat": "Ernstig",
    "polarisatie rond complottheorieën": "Ernstig",
    "desintegratie van bosnië-herzegovina": "Ernstig",
    "nan": "Ernstig",
    "griep epidemie": "Ernstig",
    "verstoring van handel door productieproblemen buitenland": "Ernstig",
    "natuurbranden": "Ernstig",
    "stralingsongeval in europa": "Aanzienlijk",
    "falen opslagtank ammoniak": "Aanzienlijk",
    "europese schuldencrisis": "Aanzienlijk",
    "cyberaanvallen kritieke infrastructuur": "Aanzienlijk",
    "ransomware zorgsector": "Aanzienlijk",
    "terroristische aanslag met een bio-wapen": "Aanzienlijk",
    "uiteenspatten van de ovse": "Aanzienlijk",
    "aanval op pride evenement": "Aanzienlijk",
    "natuurlijke aardbeving": "Aanzienlijk",
    "geweldsescalatie rechtsextremisten": "Aanzienlijk",
    "anarcho-extremisme": "Aanzienlijk",
    "buitenlandse regulering techbedrijven": "Aanzienlijk",
    "ondermijnende enclaves": "Aanzienlijk",
    "cyberspionage overheid": "Aanzienlijk",
    "georganiseerde criminaliteit door heel nederland": "Aanzienlijk",
    "uitbraak mkz onder koeien": "Aanzienlijk",
    "klassieke statelijke spionage": "Aanzienlijk",
    "innovatie nucleaire overbrengingsmiddelen": "Aanzienlijk",
    "correctie op waardering financiële activa": "Aanzienlijk",
    "misconfiguratie internetdienstverlener": "Aanzienlijk",
    "criminele inmenging bedrijfsleven": "Aanzienlijk",
    "anti-overheidsextremisme": "Aanzienlijk",
    "collateral damage": "Aanzienlijk",
    "uitbraak zoönotische variant vogelgriep": "Beperkt",
    "tekorten essentiële grondstoffen": "Beperkt",
    "overname van bedrijf dat o.a. dual-use goederen produceert": "Beperkt",
    "alleenhandelende dader": "Beperkt",
    "buitenlandse durfkapitaalinvesteringen in startups": "Beperkt",
    "tekort aan drinkwater door verzilting en vervuiling": "Ernstig",
    "gebruik van generatieve ai voor deepfakes en desinformatie": "Zeer ernstig",
    "sabotage van onderzeese infrastructuur (zoals internetkabels)": "Aanzienlijk",
    "sabotage van gnss-signalen": "Ernstig",
    "verarming biodiversiteit met effecten op voedselzekerheid": "Zeer ernstig",
    "verzwakking van cryptografie door quantumtechnologie": "Zeer ernstig",
    "verdere militarisering van de ruimte en risico op satellietaanvallen": "Ernstig",
    "strategische afhankelijkheden grondstoffen en technologie van buitenlande leveranciers": "Zeer ernstig"
};